name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup-moonbit@v1
      - name: Check
        run: moon check
      - name: Test
        run: moon test
      - name: Build
        run: moon build
